title: Plant Humanities Lab

description: Explore the cultural histories of plants and their influence on human societies

author:
  name: Ron Snyder
  email: ron@snyderjr.com

nav_pages:
  - index.md
  - about.md
  - narratives.md

max-width: 1000px

collections:
  narratives:
    output: true

show_excerpts: true
show_rss_feed: true

footer:
  show_github_link: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

contentSelector: main.post-content, div.post-content

ghbase: juncture-digital/plant-humanities/main
